//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Random_Experiment_WPF.RandomExperimentServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQLData", Namespace="http://schemas.datacontract.org/2004/07/Random_Experiment_Server.DB")]
    [System.SerializableAttribute()]
    public partial class SQLData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MedianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StdDevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mean {
            get {
                return this.MeanField;
            }
            set {
                if ((this.MeanField.Equals(value) != true)) {
                    this.MeanField = value;
                    this.RaisePropertyChanged("Mean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Median {
            get {
                return this.MedianField;
            }
            set {
                if ((this.MedianField.Equals(value) != true)) {
                    this.MedianField = value;
                    this.RaisePropertyChanged("Median");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StdDev {
            get {
                return this.StdDevField;
            }
            set {
                if ((this.StdDevField.Equals(value) != true)) {
                    this.StdDevField = value;
                    this.RaisePropertyChanged("StdDev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                if ((this.TimeZoneField.Equals(value) != true)) {
                    this.TimeZoneField = value;
                    this.RaisePropertyChanged("TimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="RandomExperimentServer.IRandomServer")]
    public interface IRandomServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IRandomServer/GetToken", ReplyAction="urn:IRandomServer/GetTokenResponse")]
        string GetToken();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IRandomServer/GetToken", ReplyAction="urn:IRandomServer/GetTokenResponse")]
        System.IAsyncResult BeginGetToken(System.AsyncCallback callback, object asyncState);
        
        string EndGetToken(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IRandomServer/SubmitStatus", ReplyAction="urn:IRandomServer/SubmitStatusResponse")]
        string SubmitStatus(string token, Random_Experiment_WPF.RandomExperimentServer.SQLData data);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IRandomServer/SubmitStatus", ReplyAction="urn:IRandomServer/SubmitStatusResponse")]
        System.IAsyncResult BeginSubmitStatus(string token, Random_Experiment_WPF.RandomExperimentServer.SQLData data, System.AsyncCallback callback, object asyncState);
        
        string EndSubmitStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IRandomServer/GetUserData", ReplyAction="urn:IRandomServer/GetUserDataResponse")]
        System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> GetUserData(string userID, System.TimeSpan time);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IRandomServer/GetUserData", ReplyAction="urn:IRandomServer/GetUserDataResponse")]
        System.IAsyncResult BeginGetUserData(string userID, System.TimeSpan time, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> EndGetUserData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IRandomServer/GetTimeZoneData", ReplyAction="urn:IRandomServer/GetTimeZoneDataResponse")]
        System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> GetTimeZoneData(int timeZone, System.TimeSpan time);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IRandomServer/GetTimeZoneData", ReplyAction="urn:IRandomServer/GetTimeZoneDataResponse")]
        System.IAsyncResult BeginGetTimeZoneData(int timeZone, System.TimeSpan time, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> EndGetTimeZoneData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRandomServerChannel : Random_Experiment_WPF.RandomExperimentServer.IRandomServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTimeZoneDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTimeZoneDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RandomServerClient : System.ServiceModel.ClientBase<Random_Experiment_WPF.RandomExperimentServer.IRandomServer>, Random_Experiment_WPF.RandomExperimentServer.IRandomServer {
        
        private BeginOperationDelegate onBeginGetTokenDelegate;
        
        private EndOperationDelegate onEndGetTokenDelegate;
        
        private System.Threading.SendOrPostCallback onGetTokenCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitStatusDelegate;
        
        private EndOperationDelegate onEndSubmitStatusDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserDataDelegate;
        
        private EndOperationDelegate onEndGetUserDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTimeZoneDataDelegate;
        
        private EndOperationDelegate onEndGetTimeZoneDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetTimeZoneDataCompletedDelegate;
        
        public RandomServerClient() {
        }
        
        public RandomServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RandomServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetTokenCompletedEventArgs> GetTokenCompleted;
        
        public event System.EventHandler<SubmitStatusCompletedEventArgs> SubmitStatusCompleted;
        
        public event System.EventHandler<GetUserDataCompletedEventArgs> GetUserDataCompleted;
        
        public event System.EventHandler<GetTimeZoneDataCompletedEventArgs> GetTimeZoneDataCompleted;
        
        public string GetToken() {
            return base.Channel.GetToken();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetToken(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetToken(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetToken(System.IAsyncResult result) {
            return base.Channel.EndGetToken(result);
        }
        
        private System.IAsyncResult OnBeginGetToken(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetToken(callback, asyncState);
        }
        
        private object[] OnEndGetToken(System.IAsyncResult result) {
            string retVal = this.EndGetToken(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTokenCompleted(object state) {
            if ((this.GetTokenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTokenCompleted(this, new GetTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTokenAsync() {
            this.GetTokenAsync(null);
        }
        
        public void GetTokenAsync(object userState) {
            if ((this.onBeginGetTokenDelegate == null)) {
                this.onBeginGetTokenDelegate = new BeginOperationDelegate(this.OnBeginGetToken);
            }
            if ((this.onEndGetTokenDelegate == null)) {
                this.onEndGetTokenDelegate = new EndOperationDelegate(this.OnEndGetToken);
            }
            if ((this.onGetTokenCompletedDelegate == null)) {
                this.onGetTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTokenCompleted);
            }
            base.InvokeAsync(this.onBeginGetTokenDelegate, null, this.onEndGetTokenDelegate, this.onGetTokenCompletedDelegate, userState);
        }
        
        public string SubmitStatus(string token, Random_Experiment_WPF.RandomExperimentServer.SQLData data) {
            return base.Channel.SubmitStatus(token, data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSubmitStatus(string token, Random_Experiment_WPF.RandomExperimentServer.SQLData data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitStatus(token, data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndSubmitStatus(System.IAsyncResult result) {
            return base.Channel.EndSubmitStatus(result);
        }
        
        private System.IAsyncResult OnBeginSubmitStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            Random_Experiment_WPF.RandomExperimentServer.SQLData data = ((Random_Experiment_WPF.RandomExperimentServer.SQLData)(inValues[1]));
            return this.BeginSubmitStatus(token, data, callback, asyncState);
        }
        
        private object[] OnEndSubmitStatus(System.IAsyncResult result) {
            string retVal = this.EndSubmitStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitStatusCompleted(object state) {
            if ((this.SubmitStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitStatusCompleted(this, new SubmitStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitStatusAsync(string token, Random_Experiment_WPF.RandomExperimentServer.SQLData data) {
            this.SubmitStatusAsync(token, data, null);
        }
        
        public void SubmitStatusAsync(string token, Random_Experiment_WPF.RandomExperimentServer.SQLData data, object userState) {
            if ((this.onBeginSubmitStatusDelegate == null)) {
                this.onBeginSubmitStatusDelegate = new BeginOperationDelegate(this.OnBeginSubmitStatus);
            }
            if ((this.onEndSubmitStatusDelegate == null)) {
                this.onEndSubmitStatusDelegate = new EndOperationDelegate(this.OnEndSubmitStatus);
            }
            if ((this.onSubmitStatusCompletedDelegate == null)) {
                this.onSubmitStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitStatusCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitStatusDelegate, new object[] {
                        token,
                        data}, this.onEndSubmitStatusDelegate, this.onSubmitStatusCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> GetUserData(string userID, System.TimeSpan time) {
            return base.Channel.GetUserData(userID, time);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUserData(string userID, System.TimeSpan time, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserData(userID, time, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> EndGetUserData(System.IAsyncResult result) {
            return base.Channel.EndGetUserData(result);
        }
        
        private System.IAsyncResult OnBeginGetUserData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            System.TimeSpan time = ((System.TimeSpan)(inValues[1]));
            return this.BeginGetUserData(userID, time, callback, asyncState);
        }
        
        private object[] OnEndGetUserData(System.IAsyncResult result) {
            System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> retVal = this.EndGetUserData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserDataCompleted(object state) {
            if ((this.GetUserDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserDataCompleted(this, new GetUserDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserDataAsync(string userID, System.TimeSpan time) {
            this.GetUserDataAsync(userID, time, null);
        }
        
        public void GetUserDataAsync(string userID, System.TimeSpan time, object userState) {
            if ((this.onBeginGetUserDataDelegate == null)) {
                this.onBeginGetUserDataDelegate = new BeginOperationDelegate(this.OnBeginGetUserData);
            }
            if ((this.onEndGetUserDataDelegate == null)) {
                this.onEndGetUserDataDelegate = new EndOperationDelegate(this.OnEndGetUserData);
            }
            if ((this.onGetUserDataCompletedDelegate == null)) {
                this.onGetUserDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserDataDelegate, new object[] {
                        userID,
                        time}, this.onEndGetUserDataDelegate, this.onGetUserDataCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> GetTimeZoneData(int timeZone, System.TimeSpan time) {
            return base.Channel.GetTimeZoneData(timeZone, time);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTimeZoneData(int timeZone, System.TimeSpan time, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTimeZoneData(timeZone, time, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> EndGetTimeZoneData(System.IAsyncResult result) {
            return base.Channel.EndGetTimeZoneData(result);
        }
        
        private System.IAsyncResult OnBeginGetTimeZoneData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int timeZone = ((int)(inValues[0]));
            System.TimeSpan time = ((System.TimeSpan)(inValues[1]));
            return this.BeginGetTimeZoneData(timeZone, time, callback, asyncState);
        }
        
        private object[] OnEndGetTimeZoneData(System.IAsyncResult result) {
            System.Collections.Generic.List<Random_Experiment_WPF.RandomExperimentServer.SQLData> retVal = this.EndGetTimeZoneData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTimeZoneDataCompleted(object state) {
            if ((this.GetTimeZoneDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTimeZoneDataCompleted(this, new GetTimeZoneDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTimeZoneDataAsync(int timeZone, System.TimeSpan time) {
            this.GetTimeZoneDataAsync(timeZone, time, null);
        }
        
        public void GetTimeZoneDataAsync(int timeZone, System.TimeSpan time, object userState) {
            if ((this.onBeginGetTimeZoneDataDelegate == null)) {
                this.onBeginGetTimeZoneDataDelegate = new BeginOperationDelegate(this.OnBeginGetTimeZoneData);
            }
            if ((this.onEndGetTimeZoneDataDelegate == null)) {
                this.onEndGetTimeZoneDataDelegate = new EndOperationDelegate(this.OnEndGetTimeZoneData);
            }
            if ((this.onGetTimeZoneDataCompletedDelegate == null)) {
                this.onGetTimeZoneDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTimeZoneDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetTimeZoneDataDelegate, new object[] {
                        timeZone,
                        time}, this.onEndGetTimeZoneDataDelegate, this.onGetTimeZoneDataCompletedDelegate, userState);
        }
    }
}
